"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import os
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()


def env_list(name, default=""):
    """Read a comma separated list from the environment."""
    return [item.strip()
            for item in os.getenv(name, default).split(",")
            if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

INSECURE_FALLBACK_KEY = (
    'django-insecure-@#x5h3zj!g+8g1v@2^b6^9$8&f1r7g$@t3v!p4#=g0r5qzj4m3'
)
SECRET_KEY = os.getenv('SECRET_KEY', default=INSECURE_FALLBACK_KEY)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:5500,http://127.0.0.1:5500",
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_rq',
    'rest_framework_simplejwt.token_blacklist',
    'auth_app.apps.AuthAppConfig',
    'corsheaders',
    'video_app.apps.VideoAppConfig',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5500,http://127.0.0.1:5500",
)

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", default="videoflix_db"),
        "USER": os.environ.get("DB_USER", default="videoflix_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD",
                                   default="supersecretpassword"),
        "HOST": os.environ.get("DB_HOST", default="db"),
        "PORT": os.environ.get("DB_PORT", default=5432)
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_LOCATION",
                                   default="redis://redis:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "videoflix"
    }
}

RQ_QUEUE_CONFIG = {
    'HOST': os.environ.get("REDIS_HOST", default="redis"),
    'PORT': os.environ.get("REDIS_PORT", default=6379),
    'DB': os.environ.get("REDIS_DB", default=0),
    'DEFAULT_TIMEOUT': 900,
    'REDIS_CLIENT_KWARGS': {},
}

RQ_QUEUES = {
    'high': {**RQ_QUEUE_CONFIG},
    'default': {**RQ_QUEUE_CONFIG},
    'low': {**RQ_QUEUE_CONFIG},
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

_PASSWORD_VALIDATION = 'django.contrib.auth.password_validation'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': f'{_PASSWORD_VALIDATION}.UserAttributeSimilarityValidator'},
    {'NAME': f'{_PASSWORD_VALIDATION}.MinimumLengthValidator'},
    {'NAME': f'{_PASSWORD_VALIDATION}.CommonPasswordValidator'},
    {'NAME': f'{_PASSWORD_VALIDATION}.NumericPasswordValidator'},
]

# Lifetime of every token built by default_token_generator. It covers the
# password reset link and the account activation link alike.
# https://docs.djangoproject.com/en/stable/ref/settings/#password-reset-timeout

PASSWORD_RESET_TIMEOUT = 24 * 60 * 60

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Video

HLS_SEGMENT_SECONDS = 6
HLS_GOP_SECONDS = 2
HLS_CRF = 23
HLS_PRESET = "fast"
HLS_AUDIO_BITRATE = "128k"
HLS_RESOLUTIONS = [480, 720, 1080]

# Timeouts are emergency brakes against stuck ffmpeg processes, not capacity
# planning. Measured in this container, 1080p needs roughly 0.7 seconds of CPU
# time per second of video, so two hours cover a movie of about three hours.

HLS_ENCODE_TIMEOUT = 2 * 60 * 60
HLS_THUMBNAIL_TIMEOUT = 60
HLS_JOB_TIMEOUT = len(HLS_RESOLUTIONS) * HLS_ENCODE_TIMEOUT + 30 * 60


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", default="localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", default=587))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", default="True") == "True"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", default="False") == "True"
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", default="noreply@videoflix.local")


FRONTEND_URL = os.environ.get("FRONTEND_URL", default="http://127.0.0.1:5500")

COOKIE_SECURE = os.environ.get("COOKIE_SECURE", default="False") == "True"

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'auth_app.api.authentication.CookieJWTAuthentication'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Videoflix API',
    'DESCRIPTION': """Backend for Videoflix, a video streaming platform.

### Authentication

Login sets `access_token` and `refresh_token` as **HttpOnly cookies**.
Protected endpoints read the access token from that cookie, not from an
`Authorization` header, so requests must be sent with `credentials: "include"`.
An expired access token can be renewed via `/api/token/refresh/` using the
refresh cookie.

### Videos

Videos are uploaded through the Django admin. A background worker (Django RQ)
then extracts a thumbnail and converts the file to HLS in 480p, 720p and 1080p.

### Streaming

Playback uses HLS: request `index.m3u8` for the desired resolution, then the
`.ts` segments it references.
""",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

AUTH_USER_MODEL = "auth_app.User"
