# Generated by Django 6.1 on 2026-08-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='available_resolutions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('done', 'DONE'), ('failed', 'FAILED')], default='pending', max_length=20),
        ),
    ]
